controller_manager:
  ros__parameters:
    update_rate: 10
    desired_cmd_timeout: 0.5

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # FL Controller
    FL_hip_controller:
      type: unitree_position_controller/UnitreePositionController
    FL_thigh_controller:
      type: unitree_position_controller/UnitreePositionController
    FL_calf_controller:
      type: unitree_position_controller/UnitreePositionController

    # FR Controller
    FR_hip_controller:
      type: unitree_position_controller/UnitreePositionController
    FR_thigh_controller:
      type: unitree_position_controller/UnitreePositionController
    FR_calf_controller:
      type: unitree_position_controller/UnitreePositionController

    # RL Controller
    RL_hip_controller:
      type: unitree_position_controller/UnitreePositionController
    RL_thigh_controller:
      type: unitree_position_controller/UnitreePositionController
    RL_calf_controller:
      type: unitree_position_controller/UnitreePositionController

    # RR Controller
    RR_hip_controller:
      type: unitree_position_controller/UnitreePositionController
    RR_thigh_controller:
      type: unitree_position_controller/UnitreePositionController
    RR_calf_controller:
      type: unitree_position_controller/UnitreePositionController

# FL Controller
FL_hip_controller:
  ros__parameters:
    update_rate: 10
    desired_cmd_timeout: 0.5
    joint_name: FL_hip_joint
    pid:
      p: 100.0
      i: 0.0
      d: 5.0
FL_thigh_controller:
  ros__parameters:
    update_rate: 10
    desired_cmd_timeout: 0.5
    joint_name: FL_thigh_joint
    pid:
      p: 300.0
      i: 0.0
      d: 8.0
FL_calf_controller:
  ros__parameters:
    update_rate: 10
    desired_cmd_timeout: 0.5
    joint_name: FL_calf_joint
    pid:
      p: 300.0
      i: 0.0
      d: 8.0

# FR Controller
FR_hip_controller:
  ros__parameters:
    update_rate: 10
    desired_cmd_timeout: 0.5
    joint_name: FR_hip_joint
    pid:
      p: 100.0
      i: 0.0
      d: 5.0
FR_thigh_controller:
  ros__parameters:
    update_rate: 10
    desired_cmd_timeout: 0.5
    joint_name: FR_thigh_joint
    pid:
      p: 300.0
      i: 0.0
      d: 8.0
FR_calf_controller:
  ros__parameters:
    update_rate: 10
    desired_cmd_timeout: 0.5
    joint_name: FR_calf_joint
    pid:
      p: 300.0
      i: 0.0
      d: 8.0

# RL Controller
RL_hip_controller:
  ros__parameters:
    update_rate: 10
    desired_cmd_timeout: 0.5
    joint_name: RL_hip_joint
    pid:
      p: 100.0
      i: 0.0
      d: 5.0
RL_thigh_controller:
  ros__parameters:
    update_rate: 10
    desired_cmd_timeout: 0.5
    joint_name: RL_thigh_joint
    pid:
      p: 300.0
      i: 0.0
      d: 8.0
RL_calf_controller:
  ros__parameters:
    update_rate: 10
    desired_cmd_timeout: 0.5
    joint_name: RL_calf_joint
    pid:
      p: 300.0
      i: 0.0
      d: 8.0

# RR Controller
RR_hip_controller:
  ros__parameters:
    update_rate: 10
    desired_cmd_timeout: 0.5
    joint_name: RR_hip_joint
    pid:
      p: 100.0
      i: 0.0
      d: 5.0
RR_thigh_controller:
  ros__parameters:
    update_rate: 10
    desired_cmd_timeout: 0.5
    joint_name: RR_thigh_joint
    pid:
      p: 300.0
      i: 0.0
      d: 8.0
RR_calf_controller:
  ros__parameters:
    update_rate: 10
    desired_cmd_timeout: 0.5
    joint_name: RR_calf_joint
    pid:
      p: 300.0
      i: 0.0
      d: 8.0
